version: '3.8'

services:
  chatgpt-proxy:
    build: .
    container_name: chatgpt-proxy
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - CHATGPT_SESSION_TOKEN=${CHATGPT_SESSION_TOKEN}
      - CHATGPT_AUTHORIZATION=${CHATGPT_AUTHORIZATION}
      - MAX_REQUESTS_PER_MINUTE=60
      - MAX_TOKENS_PER_MINUTE=40000
      - RUST_LOG=info
    restart: unless-stopped
    # 可选：使用 volumes 持久化配置或日志
    # volumes:
    #   - ./config:/app/config
    #   - ./logs:/app/logs